version: 2
jobs:
  deploy:
    docker:
        - image: simonmassey/ocd-tools:dfe80244cba579dbdcc83bb46d1203a78981b85e

    steps:
      - checkout
      - run:
          name: release chart
          command: ./github-release.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/