kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
    name: {{ printf "ocd-tools-%s" .Values.name }}
spec:
    dockerImageRepository: docker.io/simonmassey/ocd-tools
    tags:
      - name: "latest"
        from:
            kind: DockerImage
            name: docker.io/simonmassey/ocd-tools:v1.0.0